//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetResort.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public int ResortLocationID { get; set; }
        public int PetID { get; set; }
        public System.DateTime ReservationDate { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual ResortLocation ResortLocation { get; set; }
    }
}
